name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
author: LazyGon
api-version: 1.14
depend:
  - "Vault"
description: Plugin that implements signiture command.

commands:
  signiture:
    aliases: ["sign"]
    description: "Command that add formatted playername loreline."
    permission: "signiture.use"

permissions:
  signiture.use:
    default: op